In [1]:
from sklearn import preprocessing
import numpy as np
#创建一组特征数据，每一行标识一个样本，每一列标识一个特征
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])
min_max_scaler = preprocessing.MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)
print(X_train_minmax)
#将相同的缩放应用到测试集数据中
X_test = np.array([[ -3., -1.,  4.]])
X_test_minmax = min_max_scaler.transform(X_test)
print(X_test_minmax)
#打印缩放因子等属性
print(min_max_scaler.scale_)
print(min_max_scaler.min_)

[[0.5        0.         1.        ]
 [1.         0.5        0.33333333]
 [0.         1.         0.        ]]
[[-1.5         0.          1.66666667]]
[0.5        0.5        0.33333333]
[0.         0.5        0.33333333]
