In [4]:
import numpy as np


def calculate_proportion(norm_data):
    prop_data = norm_data / np.sum(norm_data, axis=0)
    return prop_data


def calculate_entropy(prop_data):
    k = 1.0 / np.log(prop_data.shape[0])
    entropy = -k * np.sum(prop_data * np.log(prop_data + 1e-12), axis=0)
    return entropy


def calculate_weights(entropy):
    d = 1 - entropy
    weights = d / np.sum(d)
    return weights


def calculate_scores(norm_data, weights):
    scores = np.dot(norm_data, weights)
    return scores


class EntropyWeightMethod(object):

    def __init__(self, data):
        self.data = data

    def normalize(self):
        norm_data = self.data / np.sqrt(np.sum(self.data ** 2, axis=0))
        return norm_data

    def core_method(self, output=True):
        def print_method():
            print("标准化数据：\n", norm_data)
            print("指标信息熵：", entropy)
            print("指标权重：", weights)
            print("评价对象的得分：", scores)

        norm_data = self.normalize()  # 步骤1：数据标准化
        prop_data = calculate_proportion(norm_data)  # 步骤2：计算各指标的比重
        entropy = calculate_entropy(prop_data)  # 步骤3：计算信息熵
        weights = calculate_weights(entropy)  # 步骤4：计算熵权
        scores = calculate_scores(norm_data, weights)  # 步骤5：加权得分
        if output:
            print_method()

import numpy as np
#from models.EntropyWeight import EntropyWeightMethod

# 原始数据
data = np.array([
    [0.9, 0.6, 0.8],
    [0.7, 0.8, 0.5],
    [0.8, 0.7, 0.9]
])

ew = EntropyWeightMethod(data)
ew.core_method()

标准化数据：
 [[0.64616234 0.49153915 0.61357199]
 [0.50257071 0.65538554 0.38348249]
 [0.57436653 0.57346234 0.69026849]]
指标信息熵： [0.99524675 0.99378666 0.97417074]
指标权重： [0.12917905 0.16885978 0.70196117]
评价对象的得分： [0.59717554 0.44477969 0.65557252]


In [20]:
import pandas as pd
import numpy as np

df = pd.read_csv('熵权法案例学生成绩.csv', header=None)
df.drop(df.columns[0])



0    1    2    3    4    5   6
1  Aͬѧ   90   90   70   90   90  80
2  Bͬѧ   60   90  100   70   90  80
3  Cͬѧ   70  100   90   80   70  70
4  Dͬѧ   90   70   80  100   80  80
5  Eͬѧ  100  100   80   70   90  60
6  Fͬѧ  100   70   70   90   80  80
7  Gͬѧ   90  100   90   70  100  80