In [1]:
import numpy as np


In [10]:
vector = np.array([0,1,2])
matrix = np.array([[1, 2, 3],
                    [4, 5, 6]
                ])

# 行数和列数

In [11]:
print(matrix.shape) # 向量维度
print(vector.shape[0])
print(matrix.shape[0]) # 行数
print(matrix.shape[1]) # 列数
# print(vector.shape[1])

(2, 3)
3
2
3


# 索引

In [13]:
print(matrix[0,1])

2


# 矩阵和向量的计算

In [15]:
vector = np.array([1,2,4])
vector2 = np.array([2,3,5])

print(np.add(vector,vector2))

print(np.dot(vector2,vector))

[3 5 9]
28


# 矩阵的数乘 转置 行列式 线性方程组求解

In [22]:
import numpy as np
# 数乘
a = 5
matrix01 = np.array([[1,2,3],[4,3,2],[4,5,6]])
scale_matrix = a * matrix01
print(scale_matrix)

# 行列式计算
a = np.linalg.det(matrix01)

# 求解线性方程组
A = np.array([[1,2],[3,4]])
b = np.array([1,3])
solution = np.linalg.solve(A,b)
print("the solution of linear system is" ,solution)

[[ 5 10 15]
 [20 15 10]
 [20 25 30]]
the solution of linear system is [1.00000000e+00 8.32667268e-17]


# 运用linalg计算线性代数 

In [23]:
import numpy as np
# If the matrix is singular, use the pseudo-inverse
pseudo_inverse_matrix = np.linalg.pinv(matrix)
print("Pseudo-inverse of the matrix:")
print(pseudo_inverse_matrix)


Pseudo-inverse of the matrix:
[[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]


In [25]:
# 计算特征值和特征向量

eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
# [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]

print(eigenvectors)


[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
# 奇异值分解

U, S, V = np.linalg.svd(matrix)
print(U)
# [[-0.21483724  0.88723069  0.40824829]
#  [-0.52058739  0.24964395 -0.81649658]
#  [-0.82633754 -0.38794278  0.40824829]]

print(S)
# [1.68481034e+01 1.06836951e+00 4.41842475e-16]

print(V)
# [[-0.47967118 -0.57236779 -0.66506441]
#  [-0.77669099 -0.07568647  0.62531805]
#  [-0.40824829  0.81649658 -0.40824829]]
